[package]
name = "matrix-multiply-benchmark-rs"
version = "0.1.0"
authors = ["Ivan Bogdanov <c3t3o7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.24.1"
clap = "2.33.3"
rand = "0.8.3"
